language: python
sudo: false
env:
    - TOXENV=py27-req2
    - TOXENV=py33-req3
    - TOXENV=py34-req3
before_install:
    - sudo apt-get -qq install graphviz > /dev/null
    - travis_retry pip install tox
script:
    - travis_retry tox
after_success:
    - coveralls