language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
    - TOXENV=py27-test
    - TOXENV=py27-install
    - TOXENV=py33-test
    - TOXENV=py33-install
    - TOXENV=py34-test
    - TOXENV=py34-install
    - TOXENV=py35-test
    - TOXENV=py35-install
    - TOXENV=py36-test
    - TOXENV=py36-install
before_install:
    - sudo apt-get -qq install graphviz > /dev/null
    - travis_retry pip install tox
    - psql -U postgres -c "CREATE DATABASE test ENCODING 'UTF8';"
    - psql -U postgres test -c "CREATE SCHEMA test;"
install: true
script:
    - travis_retry tox
after_success:
    - coveralls
