[tool.poetry]
name = "bigquery-erd"
version = "0.1.0"
description = "Creating Entity Relationship Diagrams for Google BigQuery datasets."
authors = ["Jan-Benedikt Jagusch <jan.jagusch@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-bigquery = "^2.4.0"
pygraphviz = "^1.6"
SQLAlchemy = "^1.3.20"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.6.0"
pytest = "^6.1.2"
ipykernel = "^5.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
