# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up pg
      run: |
        # stop the build if there are Python syntax errors or undefined names
        sudo apt-get install postgresql postgresql-contrib
        
    - name: Launch pg 
      run: |
        sudo pg_ctlcluster 12 main start
        psql -U postgres -c "CREATE DATABASE test ENCODING 'UTF8';"
        psql -U postgres test -c "CREATE SCHEMA test;" 
        sudo apt-get -qq install graphviz > /dev/null
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - name: Test with pytest
      run: |
        tox
